version: 2

executorType: docker
containerInfo:
  - image: circleci/android:api-27-alpha
    cmd: ["/bin/bash"]
jobs:
  build:
    working_directory: ~/android-ponewheel
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      - _JAVA_OPTIONS: "-Xmx1024m"
      - JVM_OPTS: -Xmx1024m -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1
    steps:
      - checkout
      - run:
          name: Configure Android Licences
          command: |
            mkdir "${ANDROID_HOME}/licenses" || true
            echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
            echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "${ANDROID_HOME}/licenses/android-sdk-license"
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew --no-daemon --stacktrace -PdisablePreDex androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Android build
          command: ./gradlew --no-daemon --stacktrace --max-workers 1 -PdisablePreDex assemble check
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_test_results:
          path: app/build/test-results
